#!/usr/bin/env babel-node
// @flow

const Promake = require('promake')
const fs = require('fs-extra')
const {nodeModulesRecipe} = require('../../src')

const {rule, exec, cli} = new Promake()

rule('node_modules', ['package.json'], nodeModulesRecipe(() => exec('npm i --ignore-scripts')))

cli()

